/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import lombok.Data;

import java.time.LocalDateTime;

import java.util.Objects;

import org.example.kotiki.infrastructure.domain.Cat;
/**
 * Cat
 */

 @Data
public class CatDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("birth")
  private LocalDateTime birth = null;

  @SerializedName("owner-id")
  private Integer ownerId = null;

  @SerializedName("stat-id")
  private Integer statId = null;

  public CatDTO(Cat cat){
    this.id = cat.getId();
    this.name = cat.getName();
    this.birth = cat.getBirth();
    this.ownerId = cat.getOwnerId();
    this.statId = cat.getStatId();
  }

}
