/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.Objects;
/**
 * Cats
 */

public class CatsDTO {
  @SerializedName("cats")
  private ArrayList<CatDTO> cats = new ArrayList<CatDTO>();

  public CatsDTO cats(ArrayList<CatDTO> cats) {
    this.cats = cats;
    return this;
  }

  public CatsDTO(ArrayList<CatDTO> cats) {
    this.cats = cats;
  }

  public CatsDTO addCatsItem(CatDTO catsItem) {
    this.cats.add(catsItem);
    return this;
  }

   /**
   * Get cats
   * @return cats
  **/
  @Schema(required = true, description = "")
  public ArrayList<CatDTO> getCats() {
    return cats;
  }

  public void setCats(ArrayList<CatDTO> cats) {
    this.cats = cats;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatsDTO cats = (CatsDTO) o;
    return Objects.equals(this.cats, cats.cats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cats);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cats {\n");
    
    sb.append("    cats: ").append(toIndentedString(cats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
