/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * CatsCosmetics
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CatsCosmeticsDTO {
  @SerializedName("cat-id")
  private Integer catId = null;

  @SerializedName("cosmetics")
  private List<CosmeticDTO> cosmetics = new ArrayList<CosmeticDTO>();

}
