/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import org.example.kotiki.application.cosmetic.CosmeticSet;
import org.example.kotiki.application.cosmetic.CosmeticType;
import org.example.kotiki.infrastructure.domain.Cosmetic;

import java.math.BigDecimal;
import java.util.Objects;
/**
 * Cosmetic
 */

@Data
@NoArgsConstructor
public class CosmeticDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("rarity")
  private Double rarity = null;

  @SerializedName("set")
  private String set = null;

  @SerializedName("url-key")
  private String urlKey = null;

  public CosmeticDTO(Cosmetic cosmetic) {
    this.id = cosmetic.getId();
    this.type = cosmetic.getType().toString();
    this.value = cosmetic.getValue();
    this.rarity = cosmetic.getRarity();
    this.set = cosmetic.getSet().toString();
    this.urlKey = cosmetic.getUrlKey().toString();
  }
  public CosmeticDTO(Integer id, CosmeticType type, String value, Double rarity, CosmeticSet set, String urlKey){
    this.id = id;
    this.type = type.toString();
    this.value = value;
    this.rarity = rarity;
    this.set = set.toString();
    this.urlKey = urlKey;

  }

}
