/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ErrorMessage
 */

@Data
@NoArgsConstructor
public class ErrorMessageDTO {
  @SerializedName("error-message")
  private String errorMessage = null;

  public ErrorMessageDTO (String errorMessage) {
    this.errorMessage = errorMessage;
  }

  @Schema(example = "Пользователь с таким именем уже существует", required = true, description = "")
  public String getErrorMessage() {
    return errorMessage;
  }


}
