/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * FriendRequest
 */

public class FriendRequestDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("sender-id")
  private Integer senderId = null;

  @SerializedName("recipient-id")
  private Integer recipientId = null;

  @SerializedName("status")
  private String status = null;

  public FriendRequestDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "12", required = true, description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public FriendRequestDTO senderId(Integer senderId) {
    this.senderId = senderId;
    return this;
  }

   /**
   * Get senderId
   * @return senderId
  **/
  @Schema(example = "12", required = true, description = "")
  public Integer getSenderId() {
    return senderId;
  }

  public void setSenderId(Integer senderId) {
    this.senderId = senderId;
  }

  public FriendRequestDTO recipientId(Integer recipientId) {
    this.recipientId = recipientId;
    return this;
  }

   /**
   * Get recipientId
   * @return recipientId
  **/
  @Schema(example = "12", required = true, description = "")
  public Integer getRecipientId() {
    return recipientId;
  }

  public void setRecipientId(Integer recipientId) {
    this.recipientId = recipientId;
  }

  public FriendRequestDTO status(String status) {
    this.status = status;
    return this;
  }

   /**
   * может принимать значения confirmed и not confirmed, свидетельствующие о том, была ли подтверждена заявка 
   * @return status
  **/
  @Schema(example = "not confirmed", required = true, description = "может принимать значения confirmed и not confirmed, свидетельствующие о том, была ли подтверждена заявка ")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FriendRequestDTO friendRequest = (FriendRequestDTO) o;
    return Objects.equals(this.id, friendRequest.id) &&
        Objects.equals(this.senderId, friendRequest.senderId) &&
        Objects.equals(this.recipientId, friendRequest.recipientId) &&
        Objects.equals(this.status, friendRequest.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, senderId, recipientId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FriendRequest {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
