/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import lombok.Data;
import java.time.LocalDateTime;

import javax.validation.ValidationException;

@Data
public class ProfileDTO {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("user-id")
  private Integer userId = null;

  @SerializedName("firstname")
  private String firstname = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("birth")
  private LocalDateTime birth = null;

  @SerializedName("about-me")
  private String aboutMe = null;

  @SerializedName("favorite-cat-breed")
  private String favoriteCatBreed = null;

  public void validate() throws ValidationException {
    if (firstname != null && firstname.length() > 50)
      throw new ValidationException("firstname must be less than or equal to 50");
    if (lastname != null && lastname.length() > 50)
      throw new ValidationException("lastname must be less than or equal to 50");
    if (birth != null && (birth.isBefore(LocalDateTime.now()) && birth.getYear()>=1900 ))
      throw new ValidationException("birth must be before now and past then 1900-01-01");
    if (favoriteCatBreed != null && favoriteCatBreed.length() > 50)
      throw new ValidationException("favorite-cat-breed must be less than or equal to 50");
  }
}
