/*
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.example.kotiki.infrastructure.dto;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * SendCatsCosmetics
 */
@Data
public class SendCatsCosmeticsDTO {
  @SerializedName("cat-id")
  private Integer catId = null;

  @SerializedName("cosmetics")
  private ArrayList<Integer> cosmetics = null;

}
