services:
  client-backend:
    image: client:0.0.1
    build:
      context: .\kotiki-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
#        condition: service_healthy
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - .//infrastructure//db:\docker-entrypoint-initdb.d
      - db-data:\var\lib\postgresql\data
        
  s3:
    image: scality/s3server
    ports:
      - "8000:8000"

volumes:
  db-data:
